/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AthleteId = IDL.Nat;
export const TestType = IDL.Text;
export const TestId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Athlete = IDL.Record({
  'id' : AthleteId,
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sport' : IDL.Text,
  'notes' : IDL.Text,
});
export const JumpTest = IDL.Record({
  'id' : TestId,
  'rsi' : IDL.Opt(IDL.Float64),
  'height' : IDL.Opt(IDL.Float64),
  'dropHeight' : IDL.Opt(IDL.Float64),
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'testType' : TestType,
  'athleteId' : AthleteId,
  'distance' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJumpTest' : IDL.Func(
      [
        AthleteId,
        TestType,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [TestId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAthlete' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [AthleteId],
      [],
    ),
  'deleteAthlete' : IDL.Func([AthleteId], [], []),
  'deleteJumpTest' : IDL.Func([TestId], [], []),
  'getAllAthletes' : IDL.Func([], [IDL.Vec(Athlete)], ['query']),
  'getAthlete' : IDL.Func([AthleteId], [Athlete], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJumpTestsByType' : IDL.Func(
      [AthleteId, TestType],
      [IDL.Vec(JumpTest)],
      ['query'],
    ),
  'getJumpTestsForAthlete' : IDL.Func(
      [AthleteId],
      [IDL.Vec(JumpTest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAthlete' : IDL.Func(
      [AthleteId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AthleteId = IDL.Nat;
  const TestType = IDL.Text;
  const TestId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Athlete = IDL.Record({
    'id' : AthleteId,
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sport' : IDL.Text,
    'notes' : IDL.Text,
  });
  const JumpTest = IDL.Record({
    'id' : TestId,
    'rsi' : IDL.Opt(IDL.Float64),
    'height' : IDL.Opt(IDL.Float64),
    'dropHeight' : IDL.Opt(IDL.Float64),
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'testType' : TestType,
    'athleteId' : AthleteId,
    'distance' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJumpTest' : IDL.Func(
        [
          AthleteId,
          TestType,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [TestId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAthlete' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [AthleteId],
        [],
      ),
    'deleteAthlete' : IDL.Func([AthleteId], [], []),
    'deleteJumpTest' : IDL.Func([TestId], [], []),
    'getAllAthletes' : IDL.Func([], [IDL.Vec(Athlete)], ['query']),
    'getAthlete' : IDL.Func([AthleteId], [Athlete], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJumpTestsByType' : IDL.Func(
        [AthleteId, TestType],
        [IDL.Vec(JumpTest)],
        ['query'],
      ),
    'getJumpTestsForAthlete' : IDL.Func(
        [AthleteId],
        [IDL.Vec(JumpTest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAthlete' : IDL.Func(
        [AthleteId, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };