/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Athlete {
  'id' : AthleteId,
  'age' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'sport' : string,
  'notes' : string,
}
export type AthleteId = bigint;
export interface JumpTest {
  'id' : TestId,
  'rsi' : [] | [number],
  'height' : [] | [number],
  'dropHeight' : [] | [number],
  'date' : string,
  'createdAt' : bigint,
  'testType' : TestType,
  'athleteId' : AthleteId,
  'distance' : [] | [number],
}
export type StrengthLiftType = { 'powerClean' : null } |
  { 'backSquat' : null } |
  { 'deadlift' : null };
export interface StrengthRecord {
  'id' : StrengthRecordId,
  'date' : string,
  'createdAt' : bigint,
  'athleteId' : AthleteId,
  'weightKg' : number,
  'liftType' : StrengthLiftType,
}
export type StrengthRecordId = bigint;
export type TestId = bigint;
export type TestType = string;
export interface TrainingSession {
  'id' : string,
  'fatigueLevel' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'createdBy' : Principal,
  'notes' : string,
  'athleteIds' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addJumpTest' : ActorMethod<
    [
      AthleteId,
      TestType,
      string,
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
    ],
    TestId
  >,
  'addStrengthRecord' : ActorMethod<
    [AthleteId, StrengthLiftType, number, string],
    StrengthRecordId
  >,
  'addTrainingSession' : ActorMethod<
    [string, Array<string>, bigint, string],
    TrainingSession
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAthlete' : ActorMethod<[string, bigint, string, string], AthleteId>,
  'deleteAthlete' : ActorMethod<[AthleteId], undefined>,
  'deleteJumpTest' : ActorMethod<[TestId], undefined>,
  'deleteStrengthRecord' : ActorMethod<[StrengthRecordId], undefined>,
  'deleteTrainingSession' : ActorMethod<[string], undefined>,
  'getAllAthletes' : ActorMethod<[], Array<Athlete>>,
  'getAllTrainingSessions' : ActorMethod<[], Array<TrainingSession>>,
  'getAthlete' : ActorMethod<[AthleteId], [] | [Athlete]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJumpTestsByType' : ActorMethod<[AthleteId, TestType], Array<JumpTest>>,
  'getJumpTestsForAthlete' : ActorMethod<[AthleteId], Array<JumpTest>>,
  'getStrengthRecordsByLift' : ActorMethod<
    [AthleteId, StrengthLiftType],
    Array<StrengthRecord>
  >,
  'getStrengthRecordsForAthlete' : ActorMethod<
    [AthleteId],
    Array<StrengthRecord>
  >,
  'getTrainingSessionsForAthlete' : ActorMethod<
    [string],
    Array<TrainingSession>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateAthlete' : ActorMethod<
    [AthleteId, string, bigint, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];