/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type TestType = string;
export interface TrainingSession {
    id: string;
    fatigueLevel: bigint;
    date: string;
    createdAt: bigint;
    createdBy: Principal;
    activities?: string;
    notes: string;
    athleteIds: Array<string>;
}
export type AthleteId = bigint;
export interface StrengthRecord {
    id: StrengthRecordId;
    date: string;
    createdAt: bigint;
    athleteId: AthleteId;
    weightKg: number;
    liftType: StrengthLiftType;
}
export type TestId = bigint;
export interface Athlete {
    id: AthleteId;
    age: bigint;
    name: string;
    createdAt: bigint;
    sport: string;
    notes: string;
    totalPaidKM?: number;
}
export type StrengthRecordId = bigint;
export interface JumpTest {
    id: TestId;
    rsi?: number;
    height?: number;
    dropHeight?: number;
    date: string;
    createdAt: bigint;
    testType: TestType;
    athleteId: AthleteId;
    distance?: number;
}
export enum StrengthLiftType {
    powerClean = "powerClean",
    backSquat = "backSquat",
    deadlift = "deadlift"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addJumpTest(athleteId: AthleteId, testType: TestType, date: string, height: number | null, distance: number | null, rsi: number | null, dropHeight: number | null): Promise<TestId>;
    addStrengthRecord(athleteId: AthleteId, liftType: StrengthLiftType, weightKg: number, date: string): Promise<StrengthRecordId>;
    addTrainingSession(date: string, athleteIds: Array<string>, fatigueLevel: bigint, notes: string, activities: string | null): Promise<TrainingSession>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAthlete(name: string, age: bigint, sport: string, notes: string, totalPaidKM: number | null): Promise<AthleteId>;
    deleteAllTrainingSessionsForAthlete(athleteId: string): Promise<void>;
    deleteAthlete(id: AthleteId): Promise<void>;
    deleteJumpTest(testId: TestId): Promise<void>;
    deleteStrengthRecord(recordId: StrengthRecordId): Promise<void>;
    deleteTrainingSession(sessionId: string): Promise<void>;
    getAllAthletes(): Promise<Array<Athlete>>;
    getAllTrainingSessions(): Promise<Array<TrainingSession>>;
    getAthlete(id: AthleteId): Promise<Athlete | null>;
    getCallerUserRole(): Promise<UserRole>;
    getJumpTestsByType(athleteId: AthleteId, testType: TestType): Promise<Array<JumpTest>>;
    getJumpTestsForAthlete(athleteId: AthleteId): Promise<Array<JumpTest>>;
    getStrengthRecordsByLift(athleteId: AthleteId, liftType: StrengthLiftType): Promise<Array<StrengthRecord>>;
    getStrengthRecordsForAthlete(athleteId: AthleteId): Promise<Array<StrengthRecord>>;
    getTrainingSessionsForAthlete(athleteId: string): Promise<Array<TrainingSession>>;
    isCallerAdmin(): Promise<boolean>;
    updateAthlete(id: AthleteId, name: string, age: bigint, sport: string, notes: string): Promise<void>;
    updateAthletePaid(athleteId: AthleteId, amount: number): Promise<void>;
    updateTrainingSession(sessionId: string, date: string, athleteIds: Array<string>, fatigueLevel: bigint, notes: string, activities: string | null): Promise<{
        __kind__: "ok";
        ok: TrainingSession;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Athlete as _Athlete, AthleteId as _AthleteId, JumpTest as _JumpTest, StrengthLiftType as _StrengthLiftType, StrengthRecord as _StrengthRecord, StrengthRecordId as _StrengthRecordId, TestId as _TestId, TestType as _TestType, TrainingSession as _TrainingSession, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addJumpTest(arg0: AthleteId, arg1: TestType, arg2: string, arg3: number | null, arg4: number | null, arg5: number | null, arg6: number | null): Promise<TestId> {
        if (this.processError) {
            try {
                const result = await this.actor.addJumpTest(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJumpTest(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async addStrengthRecord(arg0: AthleteId, arg1: StrengthLiftType, arg2: number, arg3: string): Promise<StrengthRecordId> {
        if (this.processError) {
            try {
                const result = await this.actor.addStrengthRecord(arg0, to_candid_StrengthLiftType_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStrengthRecord(arg0, to_candid_StrengthLiftType_n2(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async addTrainingSession(arg0: string, arg1: Array<string>, arg2: bigint, arg3: string, arg4: string | null): Promise<TrainingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.addTrainingSession(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
                return from_candid_TrainingSession_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTrainingSession(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4));
            return from_candid_TrainingSession_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAthlete(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: number | null): Promise<AthleteId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAthlete(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAthlete(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async deleteAllTrainingSessionsForAthlete(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllTrainingSessionsForAthlete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllTrainingSessionsForAthlete(arg0);
            return result;
        }
    }
    async deleteAthlete(arg0: AthleteId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAthlete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAthlete(arg0);
            return result;
        }
    }
    async deleteJumpTest(arg0: TestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJumpTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJumpTest(arg0);
            return result;
        }
    }
    async deleteStrengthRecord(arg0: StrengthRecordId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStrengthRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStrengthRecord(arg0);
            return result;
        }
    }
    async deleteTrainingSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrainingSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrainingSession(arg0);
            return result;
        }
    }
    async getAllAthletes(): Promise<Array<Athlete>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAthletes();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAthletes();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrainingSessions(): Promise<Array<TrainingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainingSessions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainingSessions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAthlete(arg0: AthleteId): Promise<Athlete | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAthlete(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAthlete(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJumpTestsByType(arg0: AthleteId, arg1: TestType): Promise<Array<JumpTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJumpTestsByType(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJumpTestsByType(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJumpTestsForAthlete(arg0: AthleteId): Promise<Array<JumpTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJumpTestsForAthlete(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJumpTestsForAthlete(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrengthRecordsByLift(arg0: AthleteId, arg1: StrengthLiftType): Promise<Array<StrengthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrengthRecordsByLift(arg0, to_candid_StrengthLiftType_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrengthRecordsByLift(arg0, to_candid_StrengthLiftType_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrengthRecordsForAthlete(arg0: AthleteId): Promise<Array<StrengthRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrengthRecordsForAthlete(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrengthRecordsForAthlete(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainingSessionsForAthlete(arg0: string): Promise<Array<TrainingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingSessionsForAthlete(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingSessionsForAthlete(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateAthlete(arg0: AthleteId, arg1: string, arg2: bigint, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAthlete(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAthlete(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateAthletePaid(arg0: AthleteId, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAthletePaid(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAthletePaid(arg0, arg1);
            return result;
        }
    }
    async updateTrainingSession(arg0: string, arg1: string, arg2: Array<string>, arg3: bigint, arg4: string, arg5: string | null): Promise<{
        __kind__: "ok";
        ok: TrainingSession;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainingSession(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainingSession(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5));
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Athlete_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Athlete): Athlete {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_JumpTest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JumpTest): JumpTest {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_StrengthLiftType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrengthLiftType): StrengthLiftType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_StrengthRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrengthRecord): StrengthRecord {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TrainingSession_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrainingSession): TrainingSession {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Athlete]): Athlete | null {
    return value.length === 0 ? null : from_candid_Athlete_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AthleteId;
    age: bigint;
    name: string;
    createdAt: bigint;
    sport: string;
    notes: string;
    totalPaidKM: [] | [number];
}): {
    id: AthleteId;
    age: bigint;
    name: string;
    createdAt: bigint;
    sport: string;
    notes: string;
    totalPaidKM?: number;
} {
    return {
        id: value.id,
        age: value.age,
        name: value.name,
        createdAt: value.createdAt,
        sport: value.sport,
        notes: value.notes,
        totalPaidKM: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.totalPaidKM))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TestId;
    rsi: [] | [number];
    height: [] | [number];
    dropHeight: [] | [number];
    date: string;
    createdAt: bigint;
    testType: _TestType;
    athleteId: _AthleteId;
    distance: [] | [number];
}): {
    id: TestId;
    rsi?: number;
    height?: number;
    dropHeight?: number;
    date: string;
    createdAt: bigint;
    testType: TestType;
    athleteId: AthleteId;
    distance?: number;
} {
    return {
        id: value.id,
        rsi: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.rsi)),
        height: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.height)),
        dropHeight: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.dropHeight)),
        date: value.date,
        createdAt: value.createdAt,
        testType: value.testType,
        athleteId: value.athleteId,
        distance: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.distance))
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StrengthRecordId;
    date: string;
    createdAt: bigint;
    athleteId: _AthleteId;
    weightKg: number;
    liftType: _StrengthLiftType;
}): {
    id: StrengthRecordId;
    date: string;
    createdAt: bigint;
    athleteId: AthleteId;
    weightKg: number;
    liftType: StrengthLiftType;
} {
    return {
        id: value.id,
        date: value.date,
        createdAt: value.createdAt,
        athleteId: value.athleteId,
        weightKg: value.weightKg,
        liftType: from_candid_StrengthLiftType_n24(_uploadFile, _downloadFile, value.liftType)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fatigueLevel: bigint;
    date: string;
    createdAt: bigint;
    createdBy: Principal;
    activities: [] | [string];
    notes: string;
    athleteIds: Array<string>;
}): {
    id: string;
    fatigueLevel: bigint;
    date: string;
    createdAt: bigint;
    createdBy: Principal;
    activities?: string;
    notes: string;
    athleteIds: Array<string>;
} {
    return {
        id: value.id,
        fatigueLevel: value.fatigueLevel,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        activities: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.activities)),
        notes: value.notes,
        athleteIds: value.athleteIds
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    powerClean: null;
} | {
    backSquat: null;
} | {
    deadlift: null;
}): StrengthLiftType {
    return "powerClean" in value ? StrengthLiftType.powerClean : "backSquat" in value ? StrengthLiftType.backSquat : "deadlift" in value ? StrengthLiftType.deadlift : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TrainingSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TrainingSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TrainingSession_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Athlete>): Array<Athlete> {
    return value.map((x)=>from_candid_Athlete_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrainingSession>): Array<TrainingSession> {
    return value.map((x)=>from_candid_TrainingSession_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JumpTest>): Array<JumpTest> {
    return value.map((x)=>from_candid_JumpTest_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StrengthRecord>): Array<StrengthRecord> {
    return value.map((x)=>from_candid_StrengthRecord_n22(_uploadFile, _downloadFile, x));
}
function to_candid_StrengthLiftType_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrengthLiftType): _StrengthLiftType {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrengthLiftType): {
    powerClean: null;
} | {
    backSquat: null;
} | {
    deadlift: null;
} {
    return value == StrengthLiftType.powerClean ? {
        powerClean: null
    } : value == StrengthLiftType.backSquat ? {
        backSquat: null
    } : value == StrengthLiftType.deadlift ? {
        deadlift: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
